version: '3.8'

services:
  # Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001
      - NEXT_PUBLIC_ALCHEMY_API_KEY=${ALCHEMY_API_KEY}
      - NEXT_PUBLIC_AUTOX_TOKEN_ADDRESS=${AUTOX_TOKEN_ADDRESS}
      - NEXT_PUBLIC_SHIFT_TOKEN_ADDRESS=${SHIFT_TOKEN_ADDRESS}
      - NEXT_PUBLIC_SWAP_CONTRACT_ADDRESS=${SWAP_CONTRACT_ADDRESS}
    depends_on:
      - backend
    networks:
      - autoxshift

  # Backend (Node.js/Express)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - FRONTEND_URL=http://frontend:3000
      - POLYGON_AMOY_RPC_URL=${POLYGON_AMOY_RPC_URL}
      - ALCHEMY_API_KEY=${ALCHEMY_API_KEY}
      - AUTOX_TOKEN_ADDRESS=${AUTOX_TOKEN_ADDRESS}
      - SHIFT_TOKEN_ADDRESS=${SHIFT_TOKEN_ADDRESS}
      - SWAP_CONTRACT_ADDRESS=${SWAP_CONTRACT_ADDRESS}
      - SIDESHIFT_API_KEY=${SIDESHIFT_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    networks:
      - autoxshift

  # PostgreSQL Database (optional)
  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=autoxshift
      - POSTGRES_USER=autoxshift
      - POSTGRES_PASSWORD=autoxshift123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - autoxshift

  # Redis Cache (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - autoxshift

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - autoxshift

volumes:
  postgres_data:
  redis_data:

networks:
  autoxshift:
    driver: bridge
